name: CI Pipeline

# Testing runs on *any* push to the repo and can also be triggered manually.
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'

    - name: Install dependencies
      run: npm install

    # - name: Run lint
    #   run: npm run lint

    - name: Run tests
      run: npm test

    # - name: Run e2e tests
    #   run: npm run test:e2e

    # - name: Run formatter
    #   run: npm run format